config/routes.rb
Rails.application.routes.draw do
  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
resource :session, controller: "clearance/sessions", only: [:create]

resources :users, controller: "clearance/users", only: [:create] do
  resource :password,
    controller: "clearance/passwords",
    only: [:create, :edit, :update]
end

get "/sign_in" => "clearance/sessions#new", as: "sign_in"
delete "/sign_out" => "clearance/sessions#destroy", as: "sign_out"
get "/sign_up" => "clearance/users#new", as: "sign_up"

  constraints Clearance::Constraints::SignedIn.new { |user| user.admin? } do
    root to: 'admin/dashboards#show', as: :admin_root
  end

  constraints Clearance::Constraints::SignedIn.new do
    root to: 'dashboards#show', as: :signed_in_root
  end

  constraints Clearance::Constraints::SignedOut.new do
    root to: 'marketing#index'
  end

  resources :users
  resources :wills
  resources :contacts
  resources :next_of_kins


end

app/models/contact.rb
class Contact < ActiveRecord::Base

  belongs_to :user

  def full_name
    "#{first_name} #{last_name}"
  end


end

app/models/next_of_kin.rb
class NextOfKin < ActiveRecord::Base

  belongs_to :user

  def full_name
    "#{first_name} #{last_name}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :contacts
  has_many :next_of_kins
  has_many :wills

  
end

app/models/will.rb
class Will < ActiveRecord::Base

  belongs_to :user

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :require_login

  def new
    @contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    @contact.user_id = current_user.id if current_user
    if @contact.save
      redirect_to root_path, notice: 'You have successfully created your Contact Info!'
    else
      render :new
    end
  end

  def show
    @contact = Contact.find(params[:id])
  end

  def edit
    @contact = Contact.find(params[:id])
  end

  def update
    @contact = Contact.find(params[:id])
    if @contact.update(contact_params)
      redirect_to contact_path(@contact), notice: 'You have successfully created your Contact Info!'
    else
      render :edit
    end
  end

  def destroy
    Contact.find(params[:id]).destroy
    redirect_to root_path, notice: "Deleted Contact!"
  end

  private

  def contact_params
    params.require(:contact).permit(:first_name, :last_name, :phone, :address_line_1,
                                 :address_line_2, :city, :state, :postal_code, :country)
  end
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController
  before_action :require_login

  def show
    @contacts = current_user.contacts
    @next_of_kins = current_user.next_of_kins
    @wills = current_user.wills
  end



end

app/controllers/marketing_controller.rb
class MarketingController < ApplicationController

  def index

  end



end

app/controllers/next_of_kins_controller.rb
class NextOfKinsController < ApplicationController
  before_action :require_login

  def new
    @next_of_kin = NextOfKin.new
  end

  def create
    @next_of_kin = NextOfKin.new(next_of_kin_params)
    @next_of_kin.user_id = current_user.id if current_user
    if @next_of_kin.save
      redirect_to root_path, notice: 'You have successfully created your Next of Kin!'
    else
      render :new
    end
  end

  def show
    @next_of_kin = NextOfKin.find(params[:id])
  end

  def edit
    @next_of_kin = NextOfKin.find(params[:id])
  end

  def update
    @next_of_kin = NextOfKin.find(params[:id])
    if @next_of_kin.update(next_of_kin_params)
      redirect_to next_of_kin_path(@next_of_kin), notice: 'You have successfully updated your Next of Kin!'
    else
      render :edit
    end
  end

  def destroy
    NextOfKin.find(params[:id]).destroy
    redirect_to root_path, notice: "Deleted Next of Kin!"
  end

  private

  def next_of_kin_params
    params.require(:next_of_kin).permit(:first_name, :last_name, :phone, :email)
  end
end

app/controllers/wills_controller.rb
class WillsController < ApplicationController
  before_action :require_login

  def new
    @will = Will.new
  end

  def create
    @will = Will.new(will_params)
    @will.user_id = current_user.id if current_user
    if @will.save
      redirect_to root_path, notice: 'You have successfully created your Will, but still need to Sign it!'
    else
      render :new
    end
  end

  def show
    @will = Will.find(params[:id])
  end

  def edit
    @will = Will.find(params[:id])
  end

  def update
    @will = Will.find(params[:id])
    if @will.update(will_params)
      redirect_to will_path(@will), notice: 'You have successfully updated your Will, but still need to Sign it!'
    else
      render :edit
    end
  end

  def destroy
    Will.find(params[:id]).destroy
    redirect_to root_path, notice: "Deleted Will!"
  end

  private

  def will_params
    params.require(:will).permit(:comments, :title, :date, :executor,
                                 :estate_plan, :burial_wishes)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  def user_facing_flashes
    flash.to_hash.slice("alert", "error", "notice", "success")
  end
end

app/views/application/_analytics.html.erb
<% if ENV["SEGMENT_KEY"] %>
  <script type="text/javascript">
    window.analytics=window.analytics||[],window.analytics.methods=["identify","group","track","page","pageview","alias","ready","on","once","off","trackLink","trackForm","trackClick","trackSubmit"],window.analytics.factory=function(t){return function(){var a=Array.prototype.slice.call(arguments);return a.unshift(t),window.analytics.push(a),window.analytics}};for(var i=0;i<window.analytics.methods.length;i++){var key=window.analytics.methods[i];window.analytics[key]=window.analytics.factory(key)}window.analytics.load=function(t){if(!document.getElementById("analytics-js")){var a=document.createElement("script");a.type="text/javascript",a.id="analytics-js",a.async=!0,a.src=("https:"===document.location.protocol?"https://":"http://")+"cdn.segment.com/analytics.js/v1/"+t+"/analytics.min.js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n)}},window.analytics.SNIPPET_VERSION="2.0.9",
    window.analytics.load("<%= ENV["SEGMENT_KEY"] %>");
    window.analytics.page();
  </script>
<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>
  <div class="flashes">
    <% user_facing_flashes.each do |key, value| -%>
      <div class="flash-<%= key %>"><%= value %></div>
    <% end -%>
  </div>
<% end %>

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

<%= render "analytics" %>

<% if Rails.env.test? %>
  <%= javascript_tag do %>
    $.fx.off = true;
    $.ajaxSetup({ async: false });
  <% end %>
<% end %>

app/views/contacts/edit.html.erb
<div class="container">
  <ul class="breadcrumb">
  <li><%= link_to "Dashboard", root_path%></li>
    <li class="active">Update Contact</li>
  </ul>
  <br />
  <div class="col-md-8 col-sm-offset-2">
    <div class="well">
      <h1>Contact Info</h1>
      <%= simple_form_for @contact do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :address_line_1 %>
        <%= f.input :address_line_2 %>
        <%= f.input :city %>
        <%= f.input :state %>
        <%= f.input :postal_code %>

        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/new.html.erb
<div class="container">
  <ul class="breadcrumb">
  <li><%= link_to "Dashboard", root_path%></li>
    <li class="active">Update Contact</li>
  </ul>
  <br />
  <div class="col-md-8 col-sm-offset-2">
    <div class="well">

      <h1>Contact Info</h1>
      <%= simple_form_for @contact do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :address_line_1 %>
        <%= f.input :address_line_2 %>
        <%= f.input :city %>
        <%= f.input :state %>
        <%= f.input :postal_code %>

        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/contacts/show.html.erb
<div class="container">
  <ul class="breadcrumb">
  <li> <%= link_to "Dashboard", root_path%></li>
    <li class="active"><%= @contact.full_name %></li>
  </ul>
  <br />
  <div class="jumbotron">
    <h1>Contact Info for <%= @contact.full_name %></h1>
      <dl class="dl-horizontal">
        <dt>Address</dt>
        <dd><%= @contact.address_line_1 %></dd>
        <dt>Address Line 2</dt>
        <dd><%= @contact.address_line_2 %></dd>
        <dt>City</dt>
        <dd><%= @contact.city %></dd>
        <dt>State</dt>
        <dd><%= @contact.state %></dd>
        <dt>Zip Code</dt>
        <dd><%= @contact.postal_code %></dd>
      </dl>
      <br />
      <%= link_to "Edit Contact", edit_contact_path, class: "btn btn-primary" %>
      <%= link_to  "Delete", contact_path(@contact), method: :delete, class: "btn btn-danger",data: { confirm: "Are you sure?" }  %>
  </div>
</div>

app/views/dashboards/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <div class="well">
        <div class="pull-right">
          <%= link_to "Update Contact Info", new_contact_path, class: "btn btn-primary" %>
        </div>
        <h1>Step 1: Contact Info</h1>
        <% @contacts.each do |contact| %>
          <ul>
            <li><%= link_to contact.full_name, contact_path(contact) %></li>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="col-md-12">
      <div class="well">
        <div class="pull-right">
          <%= link_to "Create New Next of Kin", new_next_of_kin_path, class: "btn btn-primary" %>
        </div>
        <h1>Step 2: Next of Kin</h1>
        <% @next_of_kins.each do |next_of_kin| %>
          <ul>
            <li><%= link_to next_of_kin.full_name, next_of_kin_path(next_of_kin) %></li>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="col-md-12">
      <div class="well">
        <div class="pull-right">
          <%= link_to "Create New Will", new_will_path, class: "btn btn-primary" %>
        </div>
        <h1>Step 3: Will</h1>
        <% @wills.each do |will| %>
          <ul>
            <li><%= link_to will.title, will_path(will) %></li>
          </ul>
        <% end %>
      </div>
    </div>
    <div class="col-md-12">
      <div class="well">
        <p> <%= link_to "Publish Will and Sign with Blockchain", root_path, class: "btn btn-primary btn-lg btn-block", data: { confirm: "This is where the customer will pay the annual plan, generate a pdf, e-sign with BlockSign API, prompt for two witnesses signatures.  The Will will print to pdf and also save to the Blockchain digital ledger. This version of the Will can be retrieved by the encrypted address given to the owner of the Will."} %> </p>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tag %>
  <%= stylesheet_link_tag 'application' %>
</head>
<body>
<div class="container">
  <nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-2">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <h4><%= link_to "igotawill.com", root_path %></h4>
      <!-- <a class="navbar-brand", link_to root_path ><strong>igotawill.com</strong></a> -->
    </div>

    <!-- <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-2">
      <ul class="nav navbar-nav">
        <!-- <li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li> -->
        <!-- <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul> -->
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <div class="nav navbar-nav navbar-right">
        <% if signed_in? -%>
          <%= link_to t(".sign_out"), sign_out_path, method: :delete, class: "btn btn-primary" %>
        <% else -%>
          <%= link_to "Sign in", sign_in_path, class: "btn btn-primary" %>
        <% end -%>
      </div>
    </div>
</nav>

<% if flash[:notice] %>
  <div class="alert alert-dismissible alert-success text-center" role="alert">
    <%= flash[:notice] %><button type="button" class="close" data-dismiss="alert">×</button>
  </div>
<% end %>

<br />
</div>

  <%= yield %>
  <br />
  <br />
  <br />
  <br />
  <br />
  <div class="container">
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <ul class="nav navbar-nav navbar-right">
          <li><a class="navbar-brand" href="#">igotawill.com: a Chair 9 Company</a></li>
        </ul>
      </div>
    </nav>
  </div>
</body>
</html>

app/views/marketing/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1>igotawill.com</h1>
    <p>This is a prototype for a new cloud based will service signed and timestamped with Blockchain</p>
    <p> <%= link_to "Sign Up", sign_up_path, class: "btn btn-primary btn-lg" %> </p>
  </div>

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">Secure</h3>
        </div>
        <div class="panel-body">
          Lorem ipsum dolor sit amet, eleifend in ac porta sit turpis velit, eu justo in eu id, varius phasellus sollicitudin
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">Legally Binding</h3>
        </div>
        <div class="panel-body">
          Lorem ipsum dolor sit amet, eleifend in ac porta sit turpis velit, eu justo in eu id, varius phasellus sollicitudin
        </div>
      </div>
    </div>

    <div class="col-md-4">
      <div class="panel panel-success">
        <div class="panel-heading">
          <h3 class="panel-title">Easy</h3>
        </div>
        <div class="panel-body">
          Lorem ipsum dolor sit amet, eleifend in ac porta sit turpis velit, eu justo in eu id, varius phasellus sollicitudin
        </div>
      </div>
    </div>
    <div class="col-md-6 col-md-offset-4">
      <%= image_tag("co-logo.png") %>
    </div>
</div>
</div>

app/views/next_of_kins/edit.html.erb
<div class="container">
  <ul class="breadcrumb">
  <li><%= link_to "Dashboard", root_path%></li>
    <li class="active">Update Next of Kin</li>
  </ul>
  <br />
  <div class="col-md-8 col-sm-offset-2">
    <div class="well">
      <h1>Next of Kin</h1>
      <%= simple_form_for @next_of_kin do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :phone %>
        <%= f.input :email %>

        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/next_of_kins/new.html.erb
<div class="container">
  <ul class="breadcrumb">
  <li><%= link_to "Dashboard", root_path%></li>
    <li class="active">New Next of Kin</li>
  </ul>
  <br />
  <div class="col-md-8 col-sm-offset-2">
    <div class="well">
      <h1>Next of Kin</h1>
      <%= simple_form_for @next_of_kin do |f| %>
        <%= f.input :first_name %>
        <%= f.input :last_name %>
        <%= f.input :phone %>
        <%= f.input :email %>

        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/next_of_kins/show.html.erb
<div class="container">
  <ul class="breadcrumb">
  <li><%= link_to "Dashboard", root_path%></li>
    <li class="active"><%= @next_of_kin.full_name %></li>
  </ul>
  <br />
  <div class="jumbotron">
    <h1>Contact Info for <%= @next_of_kin.full_name %></h1>
      <dl class="dl-horizontal">
        <dt>Phone</dt>
        <dd><%= @next_of_kin.phone %></dd>
        <dt>Email</dt>
        <dd><%= @next_of_kin.email %></dd>
      </dl>
      <br />
      <%= link_to "Edit Next of Kin", edit_next_of_kin_path, class: "btn btn-primary" %>
      <%= link_to  "Delete", next_of_kin_path(@next_of_kin), method: :delete, class: "btn btn-danger",data: { confirm: "Are you sure?" }  %>
  </div>
</div>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>
<br />
<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>
<br />

app/views/users/new.html.erb
<div class="container">
  <div id="clearance" class="sign-up">
    <h2><%= t(".title") %></h2>
    <br />
    <%= form_for @user do |form| %>
      <%= render partial: '/users/form', object: form %>

      <div class="submit-field">
        <%= form.submit "Sign Up", class: "btn btn-primary" %>
      </div>

    <% end %>
  </div>
</div>

app/views/wills/edit.html.erb
<div class="container">
  <ul class="breadcrumb">
  <li><%= link_to "Dashboard", root_path%></li>
    <li class="active">Update Will</li>
  </ul>
  <br />
  <div class="col-md-8 col-sm-offset-2">
    <div class="well">
      <h1>Update Will</h1>
      <%= simple_form_for @will do |f| %>
        <%= f.input :title %>
        <%= f.input :executor %>
        <%= f.input :estate_plan, as: :text %>
        <%= f.input :burial_wishes, as: :text %>
        <%= f.input :comments, as: :text %>

        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/wills/new.html.erb
<div class="container">
  <ul class="breadcrumb">
  <li><%= link_to "Dashboard", root_path%></li>
    <li class="active">New Will</li>
  </ul>
  <br />
  <div class="col-md-8 col-sm-offset-2">
    <div class="well">
      <h1>New Will</h1>
      <%= simple_form_for @will do |f| %>
        <%= f.input :title %>
        <%= f.input :executor %>
        <%= f.input :estate_plan, as: :text %>
        <%= f.input :burial_wishes, as: :text %>
        <%= f.input :comments, as: :text %>

        <%= f.button :submit, class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/wills/show.html.erb
<div class="container">
  <ul class="breadcrumb">
  <li><%= link_to "Dashboard", root_path%></li>
    <li class="active"><%= @will.title %></li>
  </ul>
  <br />
  <div class="jumbotron">
    <h1>My Will</h1>
      <dl class="dl-horizontal">
        <dt>Title</dt>
        <dd><%= @will.title %></dd>
        <dt>Executor</dt>
        <dd><%= @will.executor %></dd>
        <dt>Estate Plan</dt>
        <dd><%= @will.estate_plan %></dd>
        <dt>Burial Wishes</dt>
        <dd><%= @will.burial_wishes %></dd>
        <dt>Comments</dt>
        <dd><%= @will.comments %></dd>
      </dl>
      <br />
      <%= link_to "Edit Will", edit_will_path, class: "btn btn-primary" %>
  </div>
</div>